notifications:
  slack: zewo:VjyVCCQvTOw9yrbzQysZezD1
os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install openssl postgresql zeromq --with-libsodium libxml2;
        brew link --force openssl libxml2;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get -qq update;
        sudo apt-get -y install libssl-dev libpq-dev libzmq3-dev libxml2-dev;
    fi
install:
  - eval "$(curl -sL https://raw.githubusercontent.com/Zewo/Zewo/5254525d9da56df29346fd76e99529c22034d61d/Scripts/install-swiftenv.sh)"
script:
  - swift build --fetch # clones all dependencies
  - rm -rf Packages/*/Tests # deletes dependency's tests until duplicate Package.tests issue can be resolved in SPM. At that point, remove.
  - swift build -Xcc -I/usr/local/include -Xcc -I/usr/local/include/libxml2 -Xlinker -L/usr/local/lib -Xlinker -rpath -Xlinker $(pwd)/.build/debug/
  - swift build --configuration release -Xcc -I/usr/local/include -Xcc -I/usr/local/include/libxml2 -Xlinker -L/usr/local/lib -Xlinker -rpath -Xlinker $(pwd)/.build/release/
