os:
  - osx
  - linux
language: generic
sudo: required
osx_image: xcode8
install:
  - source install-swift.sh
  - rvm install 2.2.3
  - gem install xcpretty
script:
  - ./ci.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
