os:
  - osx
language: generic
sudo: required
dist: trusty
rvm: ruby-2.2.3
osx_image: xcode8
install:
  - eval "$(curl -sL https://raw.githubusercontent.com/QuarkX/Quark/master/swiftenv-install.sh)"
  - rvm install 2.2.3
  - bundle install
script:
  - swift build
  - swift build --configuration release
  - swift test
  - bundle exec danger
